# Generated by Django 5.2.8 on 2025-11-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['preco'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(help_text='Esse campo não pode ser nulo'),
        ),
    ]
