# Generated by Django 6.0 on 2025-12-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_produto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponibilidade',
            field=models.CharField(choices=[('D', 'Disponível'), ('I', 'Indisponível')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(),
        ),
    ]
