# Generated by Django 6.0 on 2025-12-12 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_produto_disponibilidade_alter_produto_estoque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='estoque',
            new_name='quantidade_estoque',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='disponibilidade',
        ),
        migrations.AddField(
            model_name='produto',
            name='atualizado_em',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='criado_em',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
